### ISSUE TITLE
About A3

### ISSUE THREAD

**Issue by hitors** [pascal-lab/Tai-e-assignments#15]
I have got 40/42 in A3, but all methods in test seem to be correct. Is there something wrong?
```
Analyze 42 methods, pass 40 methods
There are 516 dead Stmts in all test cases
Your submission correctly detects 516 dead Stmts
#false negatives: 0
#false positives: 2
```

**Comment by Tr4cck** [comment]
how did you solve it?

**Comment by hitors** [comment]
实在不好意思，我最后也没解决。卡住后就往后面做了，这里一直卡着。我想过参考往届的，但往届好像只有40个测试用例，可能这两个测试用例是新加的？感觉可能是多检测出了些死代码，但不知道是怎么导致的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pascal-lab/Tai-e-assignments"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月6日(星期一) 下午2:15
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [pascal-lab/Tai-e-assignments] About A3 (Issue #15)





 
how did you solve it?

**Comment by epitaphial** [comment]
It's possible that you forgot to check for side effects on the right value of the AssignStmt, which could lead to false positives.
