### ISSUE TITLE
No warning/tip for uploading without login in OJ

### ISSUE THREAD

**Issue by XChy** [pascal-lab/Tai-e-assignments#21]
When I forgot logging in my account and uploaded my assignment on [OJ](https://oj.pascal-lab.net/problem/Tai-e-1), the "uploading" tip hovered there permanently and no tips reminded me of logging in. Maybe it could be fixed?

**Comment by XChy** [comment]
It seems to be solved now.

**Comment by duang123** [comment]
hi， @XChy, 我可以问你一个问题吗？非常感谢！
你知道A1里面怎样知道DataflowResult<Node, Fact>里面的Node和Fact暴露出来的接口，最后两个函数的实现需要访问DataflowResult
  Solver.initializeBackward(CFG,DataflowResult)
  IterativeSolver.doSolveBackward(CFG,DataflowResult)
